### ISSUE TITLE
Issues while building

### ISSUE THREAD

**Issue by arunmmanoharan** [MoKee/android_packages_apps_Settings#16]
Hi I got this issue while building Mokee for the jactiveltexx.

target Java: Settings (/home/audiogod/SOKP/mokee/out/target/common/obj/APPS/Sett                                                                                                                                                             ings_intermediates/classes)
packages/apps/Settings/src/com/android/settings/cyanogenmod/MoreDeviceSettings.j                                                                                                                                                             ava:28: cannot find symbol
symbol  : class VibratorIntensity
location: package com.android.settings.hardware
import com.android.settings.hardware.VibratorIntensity;
                                    ^
packages/apps/Settings/src/com/android/settings/cyanogenmod/BootReceiver.java:77                                                                                                                                                             : cannot find symbol
symbol  : variable VibratorIntensity
location: class com.android.settings.cyanogenmod.BootReceiver
        VibratorIntensity.restore(ctx);
        ^
packages/apps/Settings/src/com/android/settings/cyanogenmod/MoreDeviceSettings.j                                                                                                                                                             ava:45: cannot find symbol
symbol  : variable VibratorIntensity
location: class com.android.settings.cyanogenmod.MoreDeviceSettings
        if (!VibratorIntensity.isSupported() || vibrator == null || !vibrator.ha                                                                                                                                                             sVibrator()) {
             ^
packages/apps/Settings/src/com/android/settings/cyanogenmod/MoreDeviceSettings.j                                                                                                                                                             ava:67: cannot find symbol
symbol  : variable VibratorIntensity
location: class com.android.settings.cyanogenmod.MoreDeviceSettings
               VibratorIntensity.isSupported();
               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
realmake: **\* [/home/audiogod/SOKP/mokee/out/target/common/obj/APPS/Settings_int                                                                                                                                                             ermediates/classes-full-debug.jar] Error 41

Hope you fix em up.

**Comment by Ryuinferno** [comment]
No such error on all our 84 devices in nightly queue, it is your device specific configuration
